services:
  bot:
    build:
      context: .
      args:
        - service_src=./src/bot
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ./src/bot:/usr/src/app/service/src:cached
      - ./src/common:/usr/src/app/service/common:cached

  planner:
    build:
      context: .
      args:
        - service_src=./src/planner
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ./src/planner:/usr/src/app/service/src:cached
      - ./src/common:/usr/src/app/service/common:cached

  crawler:
    build:
      context: .
      args:
        - service_src=./src/crawler
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ./src/crawler:/usr/src/app/service/src:cached
      - ./src/common:/usr/src/app/service/common:cached

  comparator:
    build:
      context: .
      args:
        - service_src=./src/comparator
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ./src/comparator:/usr/src/app/service/src:cached
      - ./src/common:/usr/src/app/service/common:cached

  mongo:
    image: "mongo:latest"
    logging:
      driver: none
    ports:
      - 27017:27017

  rabbitmq:
    image: "rabbitmq:latest"
    logging:
      driver: none
    ports:
      - "5672:5672"
      - "15672:15672"
